language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@1.0.0
  - npm install angularfire2@2.0.0-beta.8 --save

script:
  - ng build --prod --aot --base-href "https://bocoshapers.com/"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change  