language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@1.4.5
  - echo "export const FIREBASE_PROD = '$FIREBASE_PROD'; export const FIREBASE_DEV = '$FIREBASE_DEV';" > src/environments/firebase.keys.ts
  - cd functions && npm install && cd ..

script:
  - ng build --prod --aot --base-href "https://bocoshapers.com/"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  slack: globalshapersboulder:$SLACK_TOKEN
    
